using UnityEngine;

public class Achievements : MonoBehaviour
{
	public enum Type
	{
		TERRIBLE_FATE = 0,
		WHATS_THIS_BUTTON = 1,
		ALPHA_PILOT = 2,
		YOU_TRIED = 3,
		BEGINNERS_LUCK = 4,
		SATELLITE = 5,
		HEARTH_TO_MOON = 6,
		DEEP_IMPACT = 7,
		HARMONIC_CONVERGENCE = 8,
		MUSEUM = 9,
		DIEHARD = 10,
		PCHOOOOOOO = 11,
		GONE_IN_60_SECONDS = 12,
		CARCINOGENS = 13,
		CUTTING_IT_CLOSE = 14,
		MICAS_WRATH = 15,
		STUDIOUS = 16,
		AROUND_THE_WORLD = 17,
		SILENCED_CARTOGRAPHER = 18,
		TUBULAR = 19,
		EARLY_ADOPTER = 20,
		GRATE_FILTER = 21,
		FLAT_HEARTHER = 22,
		CELCIUS = 23,
		GHOSTS = 24,
		SLEEP_WAKE_REPEAT = 25,
		SIMULATION = 26,
		FIRE_ARROWS = 27,
		ONE_NINE = 28,
		TAKEMEALIVE = 29,
		OOFMYBONES = 30,
		FOUND_SIGNAL = 31,
		TOTAL = 32,
	}

}
