public enum JoystickButton : byte
{
	None = 0,
	FaceLeft = 1,
	FaceUp = 2,
	FaceDown = 3,
	FaceRight = 4,
	RightTrigger = 5,
	LeftTrigger = 6,
	RightStick = 7,
	LeftStick = 8,
	Start = 9,
	Select = 10,
	RightBumper = 11,
	LeftBumper = 12,
	DPadUp = 13,
	DPadDown = 14,
	DPadLeft = 15,
	DPadRight = 16,
	Triggers = 17,
	RightStickClick = 18,
	LeftStickClick = 19,
	Custom = 20,
	DS4_Share = 21,
}
